PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?class ?label WHERE { 
	?class a rdfs:Class. 
	OPTIONAL{
		?class rdfs:label ?label.
		OPTIONAL{
			FILTER(lang(?label)="en")
		}
	}
}