PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?concept ?label WHERE {
  ?concept a skos:Concept.
  OPTIONAL{
	?concept skos:prefLabel ?label.
    OPTIONAL{
		FILTER(lang(?label)="en")
	}
  }
}