# 1,964 entries
PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT  ?p ?label
WHERE
  {   { ?p  rdf:type  rdf:Property
        OPTIONAL
          { ?p  rdfs:label  ?label
            OPTIONAL
              { FILTER ( lang(?label) = "en" ) }
          }
      }
    UNION
      { ?s  ?p  ?o
        OPTIONAL
          { ?p  rdfs:label  ?label
            OPTIONAL
              { FILTER ( lang(?label) = "en" ) }
          }
      }
    UNION
      { ?p  rdf:type  owl:DatatypeProperty
        OPTIONAL
          { ?p  rdfs:label  ?label
            OPTIONAL
              { FILTER ( lang(?label) = "en" ) }
          }
      }
    UNION
      { ?p  rdf:type  owl:ObjectProperty
        OPTIONAL
          { ?p  rdfs:label  ?label
            OPTIONAL
              { FILTER ( lang(?label) = "en" ) }
          }
      }
  }