PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?p ?label WHERE { 
	?p rdf:type rdf:Property. 
	OPTIONAL {
		?p rdfs:label ?label .
		OPTIONAL {
			FILTER(LANG(?label)="en")
		}
	}
}